version: "3.8"

services:
  database:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env.dist
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
