version: "3.8"

services:
  database:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env.dist
    volumes:
      - dev_database:/var/lib/postgresql/data/

volumes:
  dev_database: