name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'


jobs:
  test_shell_scripts:
    name: Test shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run shell scripts
        run: |
          . .venv/bin/activate
          ./scripts/start_env.sh -d
          sleep 15
          ./scripts/migration.sh apply
          ./scripts/init_env.sh
          ./scripts/stop_env.sh
          ./scripts/down_env.sh

  test_app:
    name: Test FastAPI application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run flake8 & pytest
        run: |
          . .venv/bin/activate
          flake8
          ./scripts/start_env.sh -d
          cd src/
          sleep 15
          pytest

  test_docker:
    name: Test Docker image build
    runs-on: ubuntu-latest
    needs: [ test_app ]
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Docker image build
        run: docker build .