name: Tests

on:
  push:
    branches:
      - main

jobs:
  test_shell_scripts:
    name: Test shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run shell scripts
        run: |
          ./scripts/start_env.sh -d
          sleep 15
          ./scripts/migration.sh apply
          ./scripts/init_env.sh
          ./scripts/stop_env.sh
          ./scripts/down_env.sh

  test_app:
    name: Test FastAPI application
    runs-on: ubuntu-latest
    needs: [ test_shell_scripts ]
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8
      - name: Run pytest
        run: |
          ./scripts/start_env.sh -d
          sleep 15
          cd src/
          pytest
          
